"<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Stripe\Exception\InvalidRequestException: You must pass currency when passing amount_off in C:\wamp64\www\api-stripe\stripe\lib\Exception\ApiErrorException.php on line <i>38</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0050</td><td bgcolor='#eeeeec' align='right'>364744</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\api-stripe\coupons.php' bgcolor='#eeeeec'>...\coupons.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.5509</td><td bgcolor='#eeeeec' align='right'>2871880</td><td bgcolor='#eeeeec'>Stripe\Service\CouponService->create(  )</td><td title='C:\wamp64\www\api-stripe\coupons.php' bgcolor='#eeeeec'>...\coupons.php<b>:</b>15</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.5509</td><td bgcolor='#eeeeec' align='right'>2871952</td><td bgcolor='#eeeeec'>Stripe\Service\CouponService->request(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\Service\CouponService.php' bgcolor='#eeeeec'>...\CouponService.php<b>:</b>47</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.5510</td><td bgcolor='#eeeeec' align='right'>2872328</td><td bgcolor='#eeeeec'>Stripe\StripeClient->request(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\Service\AbstractService.php' bgcolor='#eeeeec'>...\AbstractService.php<b>:</b>59</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.5510</td><td bgcolor='#eeeeec' align='right'>2872880</td><td bgcolor='#eeeeec'>Stripe\ApiRequestor->request(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\BaseStripeClient.php' bgcolor='#eeeeec'>...\BaseStripeClient.php<b>:</b>134</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.5309</td><td bgcolor='#eeeeec' align='right'>2878616</td><td bgcolor='#eeeeec'>Stripe\ApiRequestor->_interpretResponse(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\ApiRequestor.php' bgcolor='#eeeeec'>...\ApiRequestor.php<b>:</b>118</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.5309</td><td bgcolor='#eeeeec' align='right'>2879664</td><td bgcolor='#eeeeec'>Stripe\ApiRequestor->handleErrorResponse(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\ApiRequestor.php' bgcolor='#eeeeec'>...\ApiRequestor.php<b>:</b>438</td></tr>
"