"<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined property: stdClass::$amount in C:\wamp64\www\api-stripe\charge.php on line <i>10</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0186</td><td bgcolor='#eeeeec' align='right'>369296</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\api-stripe\charge.php' bgcolor='#eeeeec'>...\charge.php<b>:</b>0</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined property: stdClass::$name in C:\wamp64\www\api-stripe\charge.php on line <i>11</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0186</td><td bgcolor='#eeeeec' align='right'>369296</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\api-stripe\charge.php' bgcolor='#eeeeec'>...\charge.php<b>:</b>0</td></tr>
</table></font>
{"xdebug_message":"<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )<\/span> Stripe\\Exception\\InvalidRequestException: This value must be greater than or equal to 1. in C:\\wamp64\\www\\api-stripe\\stripe\\lib\\Exception\\ApiErrorException.php on line <i>38<\/i><\/th><\/tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack<\/th><\/tr>\n<tr><th align='center' bgcolor='#eeeeec'>#<\/th><th align='left' bgcolor='#eeeeec'>Time<\/th><th align='left' bgcolor='#eeeeec'>Memory<\/th><th align='left' bgcolor='#eeeeec'>Function<\/th><th align='left' bgcolor='#eeeeec'>Location<\/th><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>1<\/td><td bgcolor='#eeeeec' align='center'>0.0186<\/td><td bgcolor='#eeeeec' align='right'>369296<\/td><td bgcolor='#eeeeec'>{main}(  )<\/td><td title='C:\\wamp64\\www\\api-stripe\\charge.php' bgcolor='#eeeeec'>...\\charge.php<b>:<\/b>0<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>2<\/td><td bgcolor='#eeeeec' align='center'>0.3616<\/td><td bgcolor='#eeeeec' align='right'>2878744<\/td><td bgcolor='#eeeeec'>Stripe\\Charge::create(  )<\/td><td title='C:\\wamp64\\www\\api-stripe\\charge.php' bgcolor='#eeeeec'>...\\charge.php<b>:<\/b>21<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>3<\/td><td bgcolor='#eeeeec' align='center'>0.3619<\/td><td bgcolor='#eeeeec' align='right'>2878816<\/td><td bgcolor='#eeeeec'>Stripe\\ApiResource::_staticRequest(  )<\/td><td title='C:\\wamp64\\www\\api-stripe\\stripe\\lib\\ApiOperations\\Create.php' bgcolor='#eeeeec'>...\\Create.php<b>:<\/b>25<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>4<\/td><td bgcolor='#eeeeec' align='center'>0.3620<\/td><td bgcolor='#eeeeec' align='right'>2879048<\/td><td bgcolor='#eeeeec'>Stripe\\ApiRequestor->request(  )<\/td><td title='C:\\wamp64\\www\\api-stripe\\stripe\\lib\\ApiOperations\\Request.php' bgcolor='#eeeeec'>...\\Request.php<b>:<\/b>63<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>5<\/td><td bgcolor='#eeeeec' align='center'>1.2382<\/td><td bgcolor='#eeeeec' align='right'>2888680<\/td><td bgcolor='#eeeeec'>Stripe\\ApiRequestor->_interpretResponse(  )<\/td><td title='C:\\wamp64\\www\\api-stripe\\stripe\\lib\\ApiRequestor.php' bgcolor='#eeeeec'>...\\ApiRequestor.php<b>:<\/b>118<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>6<\/td><td bgcolor='#eeeeec' align='center'>1.2382<\/td><td bgcolor='#eeeeec' align='right'>2889936<\/td><td bgcolor='#eeeeec'>Stripe\\ApiRequestor->handleErrorResponse(  )<\/td><td title='C:\\wamp64\\www\\api-stripe\\stripe\\lib\\ApiRequestor.php' bgcolor='#eeeeec'>...\\ApiRequestor.php<b>:<\/b>438<\/td><\/tr>\n"}"