"<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Stripe\Exception\InvalidRequestException: No such coupon: '100Desc' in C:\wamp64\www\api-stripe\stripe\lib\Exception\ApiErrorException.php on line <i>38</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0017</td><td bgcolor='#eeeeec' align='right'>370912</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\api-stripe\suscripcion.php' bgcolor='#eeeeec'>...\suscripcion.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.8115</td><td bgcolor='#eeeeec' align='right'>2983464</td><td bgcolor='#eeeeec'>Stripe\Subscription::create(  )</td><td title='C:\wamp64\www\api-stripe\suscripcion.php' bgcolor='#eeeeec'>...\suscripcion.php<b>:</b>38</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.8115</td><td bgcolor='#eeeeec' align='right'>2983544</td><td bgcolor='#eeeeec'>Stripe\ApiResource::_staticRequest(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\ApiOperations\Create.php' bgcolor='#eeeeec'>...\Create.php<b>:</b>25</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.8116</td><td bgcolor='#eeeeec' align='right'>2983776</td><td bgcolor='#eeeeec'>Stripe\ApiRequestor->request(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\ApiOperations\Request.php' bgcolor='#eeeeec'>...\Request.php<b>:</b>63</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>3.1434</td><td bgcolor='#eeeeec' align='right'>2979992</td><td bgcolor='#eeeeec'>Stripe\ApiRequestor->_interpretResponse(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\ApiRequestor.php' bgcolor='#eeeeec'>...\ApiRequestor.php<b>:</b>118</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.1434</td><td bgcolor='#eeeeec' align='right'>2981200</td><td bgcolor='#eeeeec'>Stripe\ApiRequestor->handleErrorResponse(  )</td><td title='C:\wamp64\www\api-stripe\stripe\lib\ApiRequestor.php' bgcolor='#eeeeec'>...\ApiRequestor.php<b>:</b>438</td></tr>
"